#!/bin/bash
# Display all scripts in workflow order

echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║   📜 RAGCUN Scripts (Numbered by Workflow)                ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "BEGINNER PATH (Quick Test ~5 min):"
echo "  0️⃣  ./scripts/0_gpu_info.sh"
echo "  1️⃣  ./scripts/1_prepare_data_quick.sh"
echo "  2️⃣  ./scripts/2_train_quick.sh"
echo "  3️⃣  ./scripts/3_eval.sh"
echo ""
echo "PRODUCTION PATH (~1-2 hrs):"
echo "  4️⃣  ./scripts/4_prepare_data_full.sh"
echo "  5️⃣  ./scripts/5_train_full.sh"
echo "  (3️⃣  ./scripts/3_eval.sh - reuse)"
echo ""
echo "ADVANCED TOOLS:"
echo "  6️⃣  ./scripts/6_train_custom.sh"
echo "  7️⃣  ./scripts/7_eval_all.sh"
echo "  8️⃣  ./scripts/8_monitor_training.sh"
echo "  9️⃣  ./scripts/9_hyperparameter_search.sh"
echo ""
echo "COMPLETE PIPELINES (Automated):"
echo "  99  ./scripts/99_pipeline_quick.sh"
echo "  98  ./scripts/98_pipeline_full.sh"
echo ""
echo "OTHER:"
echo "  •   ./scripts/generate_training_data.sh"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Quick start: ./scripts/99_pipeline_quick.sh"
echo "Full guide:  cat scripts/00_START_HERE.txt"
